apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jshjshjshjsh/pond_k8s_config.git'
    targetRevision: HEAD
    path: infrastructure/argocd-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd  # ArgoCD가 설치된 네임스페이스
  syncPolicy:
    automated:
      prune: true
      selfHeal: true